name: Ruff (Formatter/Linter)

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Set up Python
        uses: actions/setup-python@v5.1.1
        with:
          python-version: "3.12"

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install Python dependencies
        run: |
          poetry install

      - name: Run formatter
        run: |
          poetry run ruff format --check *.py gitbugactions/ test/

      - name: Run linter
        run: |
          poetry run ruff check --output-format=github *.py gitbugactions/
